# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/knotifications': '@latest'
    'plasma/kpipewire': '@same'

Options:
  require-passing-tests-on: [ 'Linux' ]

